### ISSUE TITLE
Add my own solutions to this repository

### ISSUE THREAD

**Issue by erfanghorbanee** [vivian-dai/PicoCTF2021-Writeup#18]
Hi!
I'm currently solving these challenges on PicoCtf and I'd like to know whether it's ok for me to keep making pull requests and adding my solutions to your repo from now on. first, I wanted to create my own repository and save my answers but your repository is quite complete and I would rather work on this one.

Have a lovely day,

Alireza.

**Comment by vivian-dai** [comment]
I don't see why you can't just fork this repository and continue adding your own solutions?

**Comment by erfanghorbanee** [comment]
thought it would be cooler to work on it with someone else,
anyway, thanks for the tip.
